### PR TITLE
update Extras/brotli sub-folder match github 1.0.9

### PR DESCRIPTION
**Pull request by twitterkb**
from https://github.com/google/brotli f4153a0

- brotli/include folder allows easier wrapping by Package.swift
- accept recommendation to update based upon security issue

  Version 1.0.9 contains a fix to "integer overflow" problem.

  This happens when "one-shot" decoding API is used (or input chunk for
  streaming API is not limited), input size (chunk size) is larger than
  2GiB, and input contains uncompressed blocks. After the overflow
  happens, memcpy is invoked with a gigantic num value, that will
  likely cause the crash.

it would appear that the "public" headers have been moved by the
maintainers to the `include/brotli` sub-folder , requiring changes to
the ZipUtilities.xcodeproj/project.pbxproj file to match.  a second
path has been added to _SEARCH_PATHS to find the <brotli/port.h> and
other headers.

- all targets build (SEARCH_PATHS had to be updated)
- tests for static lib.a target pass & .framework targets (iOS+macOS)

### CODE REVIEW

**Review by NSProgrammer — COMMENTED** [review]
There are files that had compiler flags set on them, I think just for the static analyzer.

COMPILER_FLAGS = "-w -Xanalyzer -analyzer-disable-all-checks";


Can you validate that any needed compiler flags are present?  You will have to build for all platforms and run static analyzer.

**Comment by fcanas** [comment]
There are no changes to `COMPILER_FLAGS` in the project file. I've run the static analyzer on all the targets. There are some issues in `NOZCLIUnzipMode` and `NOZXAppleCompressionCoder` in the App and noz targets that seem unrelated.

Is there anything else you'd like checked?

```
/Users/fcanas/workspace/ZipUtilities/noz/NOZCLIUnzipMode.m:185:26: nil passed to a callee that requires a non-null 1st parameter

/Users/fcanas/workspace/ZipUtilities/noz/NOZCLIUnzipMode.m:351:9: Argument to 'NSMutableArray' method 'addObject:' cannot be nil

/Users/fcanas/workspace/ZipUtilities/Extra/NOZXAppleCompressionCoder.m:238:21: Null assigned to a pointer which is expected to have non-null value
```

**Comment by niw** [comment]
@fcanas I created #103 based on this change, which has less changes, also using official v1.0.9 source code, since this patch is using edge commit, also has some unnecessary framework search path changes and also actually having wrong compiling target for additional C files.

**Comment by NSProgrammer** [comment]
Superceded by #103

Thanks all for working on this!  Great to see you in the code again!

**Pull request closed without merging**
